### ISSUE TITLE
Can't run the CometChat plugin

### ISSUE THREAD

**Issue by EdisonRizzato** [CometChat/cordova-chat-sdk-demo#1]
I get the "404 'com.cometchat.sampleapp' is not in the npm registry."

**Comment by adityagokula2210** [comment]
Hello @EdisonRizzato ,

Can you please provide us with some more information regarding the issue that you are facing. We would like to know the exact steps followed by you so as to encounter this issue.

**Comment by VIVEKKKKK** [comment]
I am having the similar error, cometchat people are not providing enough docs or guide to build app, this is really frustrating

**Comment by VIVEKKKKK** [comment]
not a single readme file is there with proper description

**Comment by adityagokula2210** [comment]
@EdisonRizzato @VIVEKKKKK 

We regret the inconvenience caused to you. We have uploaded a brand new sample app and also added a README.txt file containing the exact steps which need to be followed to run the sample app. Hope that helps..!!!

**Comment by VIVEKKKKK** [comment]
alright let me see if it works

**Comment by VIVEKKKKK** [comment]
and where do we put the plugin/SDK that we get form comet chat after paying?

**Comment by adityagokula2210** [comment]
We have published the CometChat ionic/cordova plugin to the NPM store. So now, all you need to do is add the plugin from the NPM store to your app using the same steps as you followed for the sample app.

**Comment by VIVEKKKKK** [comment]
Alright, so we need to use plugin from npm store,

1. How it checks if we have purchaed licence ? 

for debugging purpose I have started that in browser and getting following error


Uncaught ReferenceError: app is not defined =    app.initialize();


      Uncaught TypeError: Cannot read property 'querySelector' of null  =  var listeningElement = parentElement.querySelector('.listening');


forget about customisation, even compilation of this sample app is not possible without a developer. 

I think sample apps are supposed to work out of the box

Regards

**Comment by adityagokula2210** [comment]
@VIVEKKKKK 
Unfortunately, the CometChat plugin only supports iOS and Android platform. Please check the same in an android device. Please connect an android device to your machine and check with the **cordova run android** command.
