### ISSUE TITLE
issue with function launchCometChatWithID(isGroup =true)

### ISSUE THREAD

**Issue by dreamer296** [CometChat/cordova-chat-sdk-demo#3]
hi. I have successfully opened a chat window to one with another user (function launchCometChatWithID (isGroup = false);
But when opening the chat group (function launchCometChatWithID (isGroup = true)) the chat window does not appear. Even if the reponse was successful.
PLEASE HELP. THANKS.

**Comment by adityagokula2210** [comment]
We have released a new version of the CometChat plugin (version 7.2.1) to the NPM store. Please remove the older plugin and add the new one. That should resolve the issue. Please make sure you pass the GUID for the group.

**Comment by manishdeo** [comment]
Hi Aditya

I need support from your team today or tomorrow. I’m not able to integrate
with iOS. It could be helpful if you could arrange call with technical team.

Your quick response could be appreciated.



Regards
Manish Deo

**Comment by anantgarg** [comment]
Hi Manish,

If you'd like to connect with the CometChat team, please fill this form:

https://www.cometchat.com/contact-support

Thanks,
Anant
