### ISSUE TITLE
Question about  function launchCometChatWithID

### ISSUE THREAD

**Issue by trungnguyenPG** [CometChat/cordova-chat-sdk-demo#4]
Hi.
-I can open chat window one to one with function CCCometChat.launchCometChatWithID (with isGroup = false).
-but I can not open group chat window with that function (with isGroup = true) as document.
Also, when I enter groupid as roomid or guid, I get an error "invalid group id"? (Even though the chat group already exists in the database)
- Also, what function CCCometChat.launchCometChatWithID calls to any function on the backend? How can I debug them on the backend?
* note: I use php 7.2, database sql sever
Please reply as quickly as possible. Thank you very much.

**Comment by adityagokula2210** [comment]
We have released a new version of the CometChat plugin (version 7.2.1) to the NPM store. Please remove the older plugin and add the new one. That should resolve the issue. Please make sure you pass the GUID for the group.
